In [4]:
import configparser
import pymysql 
import pandas as pd

def run(cursor, query):
    cursor.execute(query)
    result = cursor.fetchall()
    column_names = [description[0] for description in cursor.description]
    df = pd.DataFrame(result, columns=column_names)
    return df

# Read database credentials from the configuration file
config = configparser.ConfigParser()
config.read('config.ini')

db_config = {
    'host': config.get('database', 'host'),
    'user': config.get('database', 'user'),
    'password': config.get('database', 'password'),
    'database': config.get('database', 'schema'),
}

# Establish a connection to the MySQL server
connection = pymysql.connect(**db_config)

# Create a cursor object to interact with the database
cursor = connection.cursor()

In [5]:
query = "SELECT * FROM company_info_full"

run(cursor, query)

,company_name,address,city,zip_code,country,organization_type,registration_body,number_of_employees,net_value
0,Slow Rush,4D Boderline Estate,London,94002,United Kingdom,Affiliate Companies,Bolagsverket,4,720000.00
1,Dirty Sprite Motion,21 St. Lucia Ave,Prague,35042,Czechia,Fiscal Sponsor,e-Äriregister,2,210000.00
2,Burning House,93 Claymore Garden,Edinburgh,60643,United Kingdom,Fiscal Sponsor,Companies House,5,339874.90
3,Passionfruit Films,4422 Weston Road,Basel,57545,Turkey,Fiscal Sponsor,Bolagsverket,5,918305.90
4,Intergalactic Studios,87 Moon Man Boulevard,Berlin,57004,Germany,For Profit,CVR Virke,3,430110.00
5,New Magic Wand,3500 Massa Estate,Augsburg,75453,Germany,For Profit,Latvijas Republikas Uzņēmumu Reģistrs,4,20005.90
6,YarnArk,8 Harcourt Street Derby,Derby,223,United Kingdom,For Profit,Companies House,0,80000.00
7,Solo Stepping Crete Films,1757 Crete Street,Warsaw,25006,Poland,For Profit,Zefix Zentraler Firmenindex,3,255400.00
8,Astroworld,90210 Rodeo Ave,Athens,46543,Greece,Non Profit,Obchodný Register,4,295084.90
9,Kryptonite Films,3 Doors Down Road,Le Havre,92940,France,Volunteer Group,CVR Virke,5,889474.90
10,Red,42 Sky Boulevard,Paris,64390,France,Volunteer Group,ARES System,3,107000.00

In [8]:
# Obtain a list of shareholders for a particular production company

query = "CALL get_shareholders_by_company('Red')"

run(cursor, query)

  first_name last_name nationality place_of_birth
0        Ava  Harrison       Italy           Rome
1       Lily      Chen       China       Shanghai

In [9]:
#  Get a list of all employees working for a specific production company

query = "CALL get_employees_by_company('Slow Rush')"

run(cursor, query)

  first_name middle_name  last_name division
0      Lucas       Henry      Evans     Crew
1     Jaguar       Lycan  Harmattan    Staff
2   Isabella      Olivia    Collins    Staff
3     Conway     Jawachi    Machine    Staff

In [ ]:
cursor.close()
connection.close()